### ISSUE TITLE
Unable to Case Object of Type

### ISSUE THREAD

**Issue by meghanareed** [MscrmTools/DamSim.ViewTransferTool#12]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidCastException: Unable to cast object of type 'Microsoft.Xrm.Tooling.Connector.CrmServiceClient' to type 'Microsoft.Xrm.Sdk.Client.OrganizationServiceProxy'.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at XrmToolBox.New.NewForm.<ManageConnectionControl>b__58_2(Object sender, ConnectionSucceedEventArgs e)
   at McTools.Xrm.Connection.ConnectionManager.SendSuccessMessage(IOrganizationService service, List`1 parameters)
   at McTools.Xrm.Connection.ConnectionManager.WorkerRunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
-----------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidCastException: Unable to cast object of type 'Microsoft.Xrm.Tooling.Connector.CrmServiceClient' to type 'Microsoft.Xrm.Sdk.Client.OrganizationServiceProxy'.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at XrmToolBox.New.NewForm.<ManageConnectionControl>b__58_2(Object sender, ConnectionSucceedEventArgs e)
   at McTools.Xrm.Connection.ConnectionManager.SendSuccessMessage(IOrganizationService service, List`1 parameters)
   at McTools.Xrm.Connection.ConnectionManager.WorkerRunWorkerCompleted(Object sender, RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by MscrmTools** [comment]
Using latest version should fix the issue
