### ISSUE TITLE
latest version does not work System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by nzhome** [MscrmTools/DamSim.ViewTransferTool#8]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at XrmToolBox.MainForm.<ManageConnectionControl>b__24_3(Object sender, ConnectionFailedEventArgs e)
   at McTools.Xrm.Connection.ConnectionManager.SendFailureMessage(String failureReason, Object parameter)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)

**Comment by MscrmTools** [comment]
This error is because the connection failed (can see it thanks to `at McTools.Xrm.Connection.ConnectionManager.SendFailureMessage(String failureReason, Object parameter)`)
